"""
    Given two strings s and t which consist of only lowercase letters.
    String t is generated by random shuffling string s and then add one more 
    letter at a random position.
    Find the letter that was added in t.

    Example:
    Input:
    s = "abcd"
    t = "abcde"
    Output:
    e
    Explanation:
                'e' is the letter that was added.
"""
#Difficulty: Easy
#54 / 54 test cases passed.
#Runtime: 24 ms
#Memory Usage: 14.1 MB

#Runtime: 24 ms, faster than 97.91% of Python3 online submissions for Find the Difference.
#Memory Usage: 14.1 MB, less than 5.37% of Python3 online submissions for Find the Difference.

class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        chars = set(t)
        for char in chars:
            if t.count(char) != s.count(char):
                return char
