"""
    Given two strings s and t which consist of only lowercase letters.
    String t is generated by random shuffling string s and then add one more 
    letter at a random position.
    Find the letter that was added in t.

    Example:
    Input:
    s = "abcd"
    t = "abcde"
    Output:
    e
    Explanation:
                'e' is the letter that was added.
"""
#Difficulty: Easy    
#54 / 54 test cases passed.
#Runtime: 40 ms
#Memory Usage: 13.6 MB
        
#Runtime: 40 ms, faster than 35.80% of Python3 online submissions for Find the Difference.
#Memory Usage: 13.6 MB, less than 98.36% of Python3 online submissions for Find the Difference.

class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        for char in t:
            if char not in s:
                return char
            else:
                s = s.replace(char, '', 1)
